server:
  port: ${PORT:8000}
  error:
    whitelabel:
      enabled: false

spring:
  # .env import
  config:
    import: optional:file:.env[.properties]
  # Using POSTGRESQL
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  cloud:
    aws:
      credentials:
        accessKey: ${AWS_ACCESS_KEY_ID}
        secretKey: ${AWS_SECRET_ACCESS_KEY}
      s3:
        bucketName: ${AWS_S3_BUCKET_NAME}
      region:
        static: ${AWS_REGION}
      stack:
        auto: false
  servlet:
    multipart:
      max-file-size: 10MB  # 허용되는 파일 크기 제한
      max-request-size: 10MB
  output:
    ansi:
      enabled: ALWAYS # 로그 색깔 추가
  #  web:
#    resources:
#      static-locations: classpath:/static/
#
#  thymeleaf:
#    cache: false
  # S3

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none #update none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  logging.level:
    org.hibernate.SQL: debug
  # org.hibernate.type: trace

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

